version: '3.8'

volumes:
  postgresql_data:

services:
  db:
    image: postgres:13
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: yamdb
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
